export default {
  FETCH_REQUEST: 'TERM/FETCH_REQUEST',
  FETCH_SUCCESS: 'TERM/FETCH_SUCCESS',
  FETCH_FAILED: 'TERM/FETCH_FAILED',

  CREATE_SUCCESS: 'TERM/CREATE_SUCCESS',
  UPDATE_SUCCESS: 'TERM/UPDATE_SUCCESS',
  DELETE_SUCCESS: 'TERM/DELETE_SUCCESS',
}
