# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.4.5'

gem 'blueprinter', '~> 1.2'
gem 'bootsnap', require: false
gem 'devise', '~> 5.0'
gem 'ostruct', '~> 0.6.3'
gem 'pagy', '~> 43.3'
gem 'pg', '~> 1.6.1'
gem 'puma', '>= 5.0'
gem 'rack-cors', '~> 3.0'
gem 'rails', '~> 8.1.2'
gem 'rswag-api', '~> 2.17'
gem 'rswag-ui', '~> 2.16'
gem 'solid_cable', '~> 3.0.12'
gem 'solid_cache', '~> 1.0.7'
gem 'solid_queue', '~> 1.3.2'
gem 'thruster', require: false
gem 'tzinfo-data', platforms: %i[windows jruby]

group :development, :test do
  gem 'brakeman', require: false
  gem 'debug', platforms: %i[mri windows], require: 'debug/prelude'
  gem 'factory_bot_rails', '~> 6.5'
  gem 'ffaker', '~> 2.24'
  gem 'fuubar', '~> 2.5.1', require: false
  gem 'pry', '~> 0.16.0'
  gem 'rspec-rails', '~> 8.0', require: false
  gem 'rswag-specs', '~> 2.16'
  gem 'rubocop-rails-omakase', require: false
end

group :test do
  gem 'airborne', '~> 0.2.13'
  gem 'rubocop-performance', '~> 1.26', require: false
  gem 'rubocop-rspec', '~> 3.6', require: false
  gem 'shoulda-matchers', '~> 7.0'
  gem 'simplecov', '~> 0.22.0', require: false
  gem 'codecov', '~> 0.2.12', require: false
  gem 'fasterer', '~> 0.11.0', require: false
end
