export const DEFAULT_RESOURCE = 'users'

export const RESOURCE_CREATE_REQUEST = 'USER_CREATE_REQUEST'
export const RESOURCE_CREATE_SUCCESS = 'USER_CREATE_SUCCEEDED'
export const RESOURCE_CREATE_FAILURE = 'USER_CREATE_FAILED'
