export default {
  FETCH_REQUEST: 'TAG/FETCH_REQUEST',
  FETCH_SUCCESS: 'TAG/FETCH_SUCCESS',
  FETCH_FAILED: 'TAG/FETCH_FAILED',

  CREATE_REQUEST: 'TAG/CREATE_REQUEST',
  CREATE_SUCCESS: 'TAG/CREATE_SUCCESS',
  CREATE_FAILED: 'TAG/CREATE_FAILED',

  UPDATE_REQUEST: 'TAG/UPDATE_REQUEST',
  UPDATE_SUCCESS: 'TAG/UPDATE_SUCCESS',
  UPDATE_FAILED: 'TAG/UPDATE_FAILED',

  DELETE_REQUEST: 'TAG/DELETE_REQUEST',
  DELETE_SUCCESS: 'TAG/DELETE_SUCCESS',
  DELETE_FAILED: 'TAG/DELETE_FAILED',
}
