export { default as gitHubSvg } from './github.svg'
export { default as mainBackgroundLightImg } from './mainBackgroundLight.jpg'
export { default as mainBackgroundDarkImg } from './mainBackgroundDark.png'
export { default as loginImg } from './loginImage.png'
export { default as personWithFlugImg } from './personWithFlug.png'
export { ExcelSvg } from './ExcelSvg'
