export const CURIOUS_BLUE = '#27AEDB'
export const BLACK = '#000'
export const WEB_ORANGE = '#FFAF00'
export const WHITE = '#FFF'
export const SEASHELL = '#F1F1F1'
export const RED = '#FF0000'
export const TURQUOISE = '#19D9A6'
export const NEPAL = '#87AFBC'
