export const DEFAULT_RESOURCE = 'sessions'

export const RESOURCE_CREATE_REQUEST = 'SESSION_CREATE_REQUEST'
export const RESOURCE_CREATE_SUCCESS = 'SESSION_CREATE_SUCCEEDED'
export const RESOURCE_CREATE_FAILURE = 'SESSION_CREATE_FAILED'

export const RESOURCE_GET_REQUEST = 'SESSION_GET_REQUEST'
export const RESOURCE_GET_SUCCESS = 'SESSION_GET_SUCCEEDED'
export const RESOURCE_GET_FAILURE = 'SESSION_GET_FAILED'

export const RESOURCE_DELETE_REQUEST = 'SESSION_DELETE_REQUEST'
export const RESOURCE_DELETE_SUCCESS = 'SESSION_DELETE_SUCCEEDED'
export const RESOURCE_DELETE_FAILURE = 'SESSION_DELETE_FAILED'

