// export const DEFAULT_RESOURCE: 'sessions'

export default {
  CREATE_REQUEST: 'SESSION/CREATE_REQUEST',
  CREATE_SUCCESS: 'SESSION/CREATE_SUCCEEDED',
  CREATE_FAILURE: 'SESSION/CREATE_FAILED',

  DELETE_REQUEST: 'SESSION/DELETE_REQUEST',
  DELETE_SUCCESS: 'SESSION/DELETE_SUCCEEDED',
  DELETE_FAILURE: 'SESSION/DELETE_FAILED',
}
