export default {
  CREATE_REQUEST: 'SESSION/CREATE_REQUEST',
  CREATE_SUCCESS: 'SESSION/CREATE_SUCCESS',
  CREATE_FAILED: 'SESSION/CREATE_FAILED',

  DELETE_REQUEST: 'SESSION/DELETE_REQUEST',
  DELETE_SUCCESS: 'SESSION/DELETE_SUCCESS',
  DELETE_FAILED: 'SESSION/DELETE_FAILED',
}
