inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4.5
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Layout/LineLength:
  Max: 120

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/ModuleLength:
  Exclude:
    - spec/**/*.rb

RSpec/EmptyExampleGroup:
  Exclude:
    - spec/requests/**/*.rb

RSpec/ImplicitExpect:
  EnforcedStyle: should

RSpec/ExampleLength:
  Enabled: false
