# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.4.5'

gem 'bootsnap', require: false
gem 'devise', '~> 4.9'
gem 'kamal', require: false
gem 'pg', '~> 1.6.1'
gem 'puma', '>= 5.0'
gem 'rabl', '~> 0.17.0'
gem 'rack-cors', '~> 3.0'
gem 'rails', '~> 8.0.2', '>= 8.0.2.1'
gem 'rswag-api', '~> 2.16'
gem 'rswag-ui', '~> 2.16'
gem 'solid_cable'
gem 'solid_cache'
gem 'solid_queue'
gem 'thruster', require: false
gem 'tzinfo-data', platforms: %i[windows jruby]

group :development, :test do
  gem 'brakeman', require: false
  gem 'debug', platforms: %i[mri windows], require: 'debug/prelude'
  gem 'factory_bot_rails', '~> 6.5'
  gem 'ffaker', '~> 2.24'
  gem 'fuubar', '~> 2.5.1', require: false
  gem 'pry', '~> 0.15.2'
  gem 'rspec-rails', '~> 8.0', require: false
  gem 'rswag-specs', '~> 2.16'
  gem 'rubocop-rails-omakase', require: false
end

group :test do
  gem 'airborne', '~> 0.2.13'
  gem 'rubocop-performance', '~> 1.25', require: false
  gem 'rubocop-rspec', '~> 3.6', require: false
  gem 'shoulda-matchers', '~> 6.5'
  gem 'simplecov', '~> 0.22.0', require: false
  gem 'codecov', '~> 0.2.12', require: false
  gem 'fasterer', '~> 0.11.0', require: false
end
