export const DEFAULT_RESOURCE = 'words'

export const RESOURCE_CREATE_REQUEST = 'WORD_CREATE_REQUEST'
export const RESOURCE_CREATE_SUCCESS = 'WORD_CREATE_SUCCEEDED'
export const RESOURCE_CREATE_FAILURE = 'WORD_CREATE_FAILED'
