require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/ModuleLength:
  Exclude:
    - spec/**/*.rb
