# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.1'

gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'devise', '~> 4.8.0'
gem 'pg', '~> 1.5.4'
gem 'puma', '~> 5.6'
gem 'rabl', '~> 0.14.5'
gem 'rack-cors', '~> 1.1.1'
gem 'rails', '~> 6.1.4', '>= 6.1.4.1'
gem 'rswag-api', '~> 2.4.0'
gem 'rswag-ui', '~> 2.4.0'

group :development, :test do
  gem 'factory_bot_rails', '~> 6.2.0'
  gem 'ffaker', '~> 2.20.0'
  gem 'fuubar', '~> 2.5.1', require: false
  gem 'pry', '~> 0.14.1'
  gem 'rspec-rails', '~> 4.0.2', require: false
  gem 'rswag-specs', '~> 2.4.0'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring', '~> 3.0.0'
end

group :test do
  gem 'airborne', '~> 0.3.7'
  gem 'codecov', '~> 0.6.0', require: false
  gem 'fasterer', '~> 0.9.0', require: false
  gem 'rubocop', '~> 1.22.1', require: false
  gem 'rubocop-performance', '~> 1.11.5', require: false
  gem 'rubocop-rspec', '~> 2.5.0', require: false
  gem 'shoulda-matchers', '~> 4.0'
  gem 'simplecov', '~> 0.21.2', require: false
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
